VBIMusic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from VBIMusicApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
	url(r'^$', views.user_login, name='login'),
    url(r'^VBIMusicApp/', include('VBIMusicApp.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
]

VBIMusicApp/urls.py
from django.conf.urls import url
from VBIMusicApp import views

app_name = 'VBIMusicApp'

urlpatterns = [
	url(r'^user_login/$',views.user_login, name='user_login'),
	url(r'^$', views.index, name='index'),
	url(r'^list_all_songs/$', views.list_all_songs, name='list_all_songs'),
	url(r'^search_song/$', views.search_song, name='search_song'),
	url(r'^list_all_playlists/$', views.list_all_playlists, name='list_all_playlists'),
	url(r'^view_playlist/$', views.view_playlist, name='view_playlist'),
	url(r'^create_playlist/$', views.create_playlist, name='create_playlist'),
	url(r'^list_songs_to_add_to_playlist/$', views.list_songs_to_add_to_playlist, name='list_songs_to_add_to_playlist'),
	url(r'^add_song_to_playlist/$', views.add_song_to_playlist, name='add_song_to_playlist'),
	url(r'^search_in_playlist/$', views.search_in_playlist, name='search_in_playlist'),
	url(r'^shuffle_songs/$', views.shuffle_songs, name='shuffle_songs'),
]

VBIMusicApp/models.py
from django.db import models
import uuid
import datetime

class Singer(models.Model):      
	id = models.AutoField(primary_key=True)
	singer_name = models.CharField(max_length=50, unique=True)

	def __str__(self):
		return self.singer_name

class Song(models.Model):
	id = models.AutoField(primary_key=True)
	song_title = models.CharField(max_length=50, db_index=True)
	album =  models.CharField(max_length=50, db_index=True)
	singers = models.ManyToManyField(
        Singer,
        through='SongSingerMapping'
    )
	play_time = models.CharField(max_length=50)
	updated_by = models.ForeignKey('User', on_delete=models.PROTECT)
	updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
	active = models.BooleanField(default=True)

	def __str__(self):
		return str(self.id)

class SongSingerMapping(models.Model):
	class Meta:
		unique_together = (('song_id', 'singer_id'),)

	id = models.AutoField(primary_key=True)
	song_id = models.ForeignKey('Song', on_delete=models.CASCADE, related_name='songs')
	singer_id = models.ForeignKey('Singer', on_delete=models.CASCADE, related_name='singers')

	def __str__(self):
		return str(self.id)

class Playlist(models.Model):
	id = models.AutoField(primary_key=True)
	uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
	playlist_name = models.CharField(max_length=25, unique=True)
	songs = models.ManyToManyField(
        Song,
        through='SongPlayListMapping'
    )
	user_id = models.ForeignKey('User', on_delete=models.PROTECT)
	created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

	def __str__(self):
		return str(self.id)

class SongPlayListMapping(models.Model):
	class Meta:
		unique_together = (('playlist_id', 'song_id'),)

	id = models.AutoField(primary_key=True)
	playlist_id = models.ForeignKey('Playlist', on_delete=models.CASCADE)
	song_id = models.ForeignKey('Song', on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return str(self.id)

class User(models.Model):
	id = models.AutoField(primary_key=True)
	username = models.CharField(max_length=10, unique=True)
	password = models.CharField(max_length=50)
	usergroup = models.CharField(max_length=20)
	updated_by = models.ForeignKey('User', on_delete=models.PROTECT, null=True, blank=True)
	updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
	active = models.BooleanField(default=True)

	def __str__(self):
		return '%s %s' % (self.id, self.username)

VBIMusicApp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.response import Response
import json
import random
from VBIMusicApp.models import Song, Singer, SongSingerMapping, Playlist, SongPlayListMapping, User

# Create your views here.

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username = username, password = password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect('/VBIMusicApp/')

			else:
				return HttpResponse('Account is not active')

		else:
			print('Login failed!')
			print("Username : {} and password : {}", format(username, password))
			return HttpResponse("Invalid login details")

	else:
		return render(request,'VBIMusicApp/login.html',{})

@login_required
def user_logout(request):
	logout(request)
	return render(request, 'VBIMusicApp/login.html')

def index(request):
	return render(request, 'VBIMusicApp/index.html')

def song_template(queryset):
	songs = []
	for song in queryset:
		singers_str = ','.join(list(song.singers.all().values_list('singer_name', flat=True)))
		songs.append({'song_id':song.id, 'song_title':song.song_title, 'singers': singers_str, 'album' : song.album, 'play_time': song.play_time})
	return songs

@login_required
@api_view(['GET'])
def list_all_songs(request):
	song_queryset = Song.objects.all().prefetch_related('singers')
	all_songs = song_template(song_queryset)
	return Response(data = all_songs, status=status.HTTP_200_OK)

@login_required
@api_view(['GET'])
def search_song(request):
	search_text = request.GET['search_text']
	song_queryset = Song.objects.filter(song_title__icontains=search_text).prefetch_related('singers')
	suggestions = song_template(song_queryset)
	return Response(data = suggestions, status=status.HTTP_200_OK)

@login_required
@api_view(['GET'])
def list_all_playlists(request):
	user_id = request.GET['user_id']
	all_playlists = []
	playlist_queryset = Playlist.objects.filter(user_id__exact=user_id)
	for playlist in playlist_queryset:
		all_playlists.append({'playlist_id':playlist.uuid, 'playlist_name':playlist.playlist_name, 'created_at': playlist.created_at.strftime("%d-%m-%Y %H:%M:%S")})
	return Response(data = all_playlists, status=status.HTTP_200_OK)

@login_required
@api_view(['GET'])
def view_playlist(request):
	playlist_id = request.GET['playlist_id']
	songs_list = song_template(Playlist.objects.filter(uuid=playlist_id).prefetch_related('songs')[0].songs.all().order_by('-songplaylistmapping'))
	return Response(data = songs_list, status=status.HTTP_200_OK)

@login_required
@api_view(['POST'])
def create_playlist(request):
	playlist_name = request.POST.get('playlist_name')
	user_id = request.POST.get('user_id')
	all_playlists = []
	user = User.objects.only('id').get(id=user_id)
	playlist = Playlist.objects.create(playlist_name=playlist_name, user_id=user)
	playlist.save()
	playlist_queryset = Playlist.objects.filter(user_id__exact=user_id)
	for playlist in playlist_queryset:
		all_playlists.append({'playlist_id':playlist.uuid, 'playlist_name':playlist.playlist_name, 'created_at': playlist.created_at.strftime("%d-%m-%Y %H:%M:%S")})
	print(all_playlists)
	return Response(data = all_playlists, status=status.HTTP_200_OK)

@login_required
@api_view(['GET'])
def list_songs_to_add_to_playlist(request):
	playlist_id = request.GET['playlist_id']
	song_id_list = list(Playlist.objects.filter(uuid=playlist_id).prefetch_related('songs')[0].songs.values_list('id', flat=True))
	songs_list = song_template(Song.objects.exclude(pk__in=song_id_list))
	return Response(data = songs_list, status=status.HTTP_200_OK)

@login_required
@api_view(['POST'])
def add_song_to_playlist(request):
	playlist_id = request.POST.get('playlist_id')
	song_id = request.POST.get('song_id')
	playlist = Playlist.objects.only('id').get(uuid=playlist_id)
	song = Song.objects.only('id').get(id=song_id)
	song_mapper = SongPlayListMapping.objects.create(playlist_id=playlist, song_id=song)
	song_mapper.save()
	songs_list = song_template(Playlist.objects.filter(uuid=playlist_id).prefetch_related('songs')[0].songs.all().order_by('-songplaylistmapping'))
	return Response(data = songs_list, status=status.HTTP_200_OK)

@login_required
@api_view(['GET'])
def search_in_playlist(request):
	playlist_id = request.GET['playlist_id']
	search_text = request.GET['search_text']
	print(playlist_id, search_text);
	song_id_list = list(Playlist.objects.filter(uuid=playlist_id).prefetch_related('songs')[0].songs.values_list('id', flat=True))
	songs_list = []
	if (list(Song.objects.exclude(pk__in=song_id_list).filter(song_title__icontains=search_text))) != 0:
		songs_list = song_template(Song.objects.exclude(pk__in=song_id_list).filter(song_title__icontains=search_text))
	return Response(data = songs_list, status=status.HTTP_200_OK)

@login_required
@api_view(['GET'])
def shuffle_songs(request):
	playlist_id = request.GET['playlist_id']
	song_id_list = list(Playlist.objects.filter(uuid=playlist_id).prefetch_related('songs')[0].songs.values_list('id', flat=True))
	songs_list = song_template(Song.objects.filter(pk__in=song_id_list).order_by('?'))
	print(songs_list)
	return Response(data = songs_list, status=status.HTTP_200_OK)

templates/VBIMusicApp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VBI Music</title>

    <!-- Bootstrap core CSS -->
  	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/metro-all.min.css' %}"/>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/metro.min.js' %}" defer></script>
    <script src="{% static 'js/myjs.js' %}"></script>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
    <script type="text/javascript">
      $( document ).ready(function() {
          list_all_songs();
          $('#_allsongs .default-icon-cross').click(function() {
            list_all_songs();
          });
          $('.all-songs').click(function() {
            list_all_songs();
          });
      });
    </script>
  </head>

  <!-- <body style="text-align: center;"> -->
  <body>
  	<div style="width: 100%">
  		{% block body_block %}
  		{% endblock %}
  	</div>
  </body>
</html>

templates/VBIMusicApp/index.html
{% extends 'VBIMusicApp/base.html' %}
{% load staticfiles %}
{% block body_block %}

<style type="text/css">
	body{
		display: block !important;
	}
</style>

<div class="grid">
    <div class="row">
        <div class="cell-1">
            <div></div>
        </div>
        <div class="cell-10">

        	<!-- topbar starts -->
            <ul class="h-menu" style="color: white; background-color: #006497;">
                <li><a href="#">VBI - Your music companion!</a></li>
                {% if user.is_authenticated %}
                  	<!-- <p style="display: inline-block;color: blue;">Hi {{ user.get_username }},</p> -->
                    <!-- <a href="{% url 'logout' %}">Logout</a> -->
                	
                    <li style="float: right;"><a href="{% url 'logout' %}">Logout</a></li>
                	<li style="float: right;"><a href="#">Welcome {{ user.get_username }}</a></li>
                {% endif %}
            </ul>
            <!-- topbar ends -->

            <!-- tab section starts -->
            <ul data-cls-tabs="flex-justify-center mt-2" data-role="tabs" data-expand="true">
                <li class="all-songs"><a href="#_allsongs">All Songs</a></li>
                <li onclick='list_all_playlists()'><a href="#_playlists">Playlists</a></li>
            </ul>
            <!-- tab section ends -->
            
            <!-- tabeselector is id href attr -->
            <div class="border bd-default no-border-top p-2">
                <div id="_allsongs">
                    <!-- search section starts -->
                    <form action="javascript:" onsubmit="search_song()">
                        <input id="search_text" type="text" data-role="input" data-search-button-click="custom"
                            data-on-search-button-click="mySubmitSearch" data-history="true"
                            data-prepend="Search Songs:">
                    </form>
                    <!-- search section ends -->
                    <!-- list song section starts -->
                                       
                    <div class="items-list" id='items-list'>
                    </div>
                    <!-- list song section ends -->
                </div>
                <div id="_playlists">
                	<div class="no-playlists">
                    	<h5><small> No playlist available </small></h5>
                	</div>
                	<div class="no-songs">
                    	<h5><small> No song available </small></h5>
                	</div>
                	<div class="items-list playlist-items" id='playlist-items'>
                    </div>
                    <div class="col-md-12 text-center playlist-items">
						<button class="button info" onclick="openPlaylistDialog()">Create Playlist</button>
                    </div>
                    <div class="col-md-12 playlist-header" id="playlist-header">
                    </div>
                    <div class="col-md-12 text-center">
						<button class="button info shuffle-btn" onclick="shuffle_songs()">Shuffle Play</button>
						<button class="button info add-btn" onclick="list_songs_to_add_to_playlist()">Add Song</button>
                    </div>
                    <form class="playlist-search" id="playlist-search" action="javascript:" onsubmit="search_in_playlist()">
                        <input id="search_text" type="text" data-role="input" data-search-button-click="custom"
                            data-on-search-button-click="mySubmitSearch" data-history="true"
                            data-prepend="Search Songs:">
                    </form>
                    <div class="items-list playlist-songs" id='playlist-songs'>
                    </div>
                </div>
            </div>
        </div>
        <div class="cell-1">
            <div></div>
        </div>
    </div>
</div>

<!-- Playlist Modal -->
<div class="dialog" data-role="dialog" id="playlistDialog">
    <div class="dialog-title">Create Playlist</div>
    <div class="dialog-content">
        <form action="javascript:" method="post">
        	{% csrf_token %}
            <div class="form-group">
		        <div class="row mb-12">
			        <label class="cell-sm-4">Playlist Name</label>
			        <div class="cell-sm-8">
			            <input type="text" id="playlist-name" class="metro-input">
			        </div>
			    </div>
		    </div>
        </form>
    </div>
    <div class="dialog-actions">
        <button class="button success js-dialog-close" onclick="create_playlist()">Create</button>
        <button class="button warning js-dialog-close" onclick="">Cancel</button>
    </div>
</div>

{% endblock %}

templates/VBIMusicApp/login.html
{% extends 'VBIMusicApp/base.html' %}
{% block body_block %}

<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-login my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Login</h5>
            <form class="form-login" action="{% url 'VBIMusicApp:user_login' %}" method="post">
              {% csrf_token %}
              <div class="form-label-group">
                <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
                <label for="username">Username</label>
              </div>

              <div class="form-label-group">
                <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
                <label for="password">Password</label>
              </div>

              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Remember password</label>
              </div>
              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Login</button>
              <hr class="my-4">
            </form>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock %}